name: klizma
version: 0.0.0-nullsafety.0
description: A minimalistic DI (Dependency Injection) container for Dart.
homepage: https://github.com/f3ath/klizma

environment:
  sdk: '>=2.12.0-29 <3.0.0'

dev_dependencies:
  pedantic: ^1.10.0-nullsafety
  test: ^1.16.0-nul
  test_coverage: ^0.5.0
