name: klizma
version: 0.2.0
description: A minimalistic Dependency Injection and Service Locator implementation in Dart.
homepage: https://github.com/f3ath/klizma

environment:
  sdk: '>=2.12.0 <3.0.0'

dev_dependencies:
  pedantic: ^1.11.0
  test: ^1.16.8
  coverage: ^1.0.2
  check_coverage: ^0.0.2
